// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Note struct {
	ID        string      `json:"id"`
	Author    string      `json:"author"`
	Message   string      `json:"message"`
	UpdatedAt string      `json:"updated_at"`
	CreatedAt string      `json:"created_at"`
	UserID    interface{} `json:"user_id"`
	Verified  int64       `json:"verified"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	UpdatedAt string `json:"updated_at"`
	CreatedAt string `json:"created_at"`
	Verified  int64  `json:"verified"`
}
